// Array.isArray()
// Array.prototype.valueOf()
// Array.prototype.toString()
// Array.prototype.pop()
// Array.prototype.push()
// Array.prototype.shift()
// Array.prototype.unshift()
// Array.prototype.reverse()
// Array.prototype.reduce()
// Array.prototype.sort()
// Array.prototype.some()
// Array.prototype.every()
// Array.prototype.forEach()
// Array.prototype.map()
// Array.prototype.concat()
// Array.prototype.join()
// Array.prototype.slice()
// Array.prototype.splice()
// Array.prototype.filter()
// Array.prototype.find()
// Array.prototype.findIndex()
// Array.from()
// Array.of()
// Array.prototype.copyWithin()
// Array.prototype.fill()
// Array.prototype.entries()/Array.prototype.values()/Array.prototype.keys()
// Array.prototype.includes()
// Array.prototype.flat()
// Array.prototype.flatMap()

var arr = [1, 2, 3]
// var res = arr.fill(5, 0, 2)
// var res = arr.join('-')
// var res = arr.slice(0, 1)
// var res = arr.splice(0, 1, 3)
// var res = arr.concat([0, 1, 3])
var res = arr.reduce((prev, curr, currIdx, arr) => {
  
})
console.log(res, 'res')
console.log(arr, 'arr')